backend:
  name: gitlab
  repo: mobagenie/mobagenie.my.id
  branch: master
media_folder: "static/netlify/assets"
public_folder: "../../"
display_url: https://admin-mobagenie.netlify.app/
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    show_preview_links: true
    fields: # The fields for each document, usually in front matter
      # - {label: "Title", name: "title", widget: "string"}
      # - {label: "Description", name: "description", widget: "string"}
      # - {label: "Description", name: "description", widget: "string"}      
      # - {label: "Body", name: "body", widget: "markdown"}
      # - {label: "Featured Image", name: "image", widget: "image", required: false}
      # - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      # - {label: "Categories", name: "categories", widget: "list"}
      
      - {label: "Title", name: "title", widget: "string"}
      - {label: "post_highlight", name: "post_highlight", widget: "string"}
      - {label: "author", name: "author", widget: "string", required: false}
      - {label: "date", name: "date", widget: "datetime", required: false}
      - {label: "PublishDate", name: "PublishDate", widget: "datetime", required: true}
      - {label: "Lastmod", name: "Lastmod", widget: "datetime", required: false}
      - {label: "slug", name: "slug", widget: "list"}
      - {label: "categories", name: "categories", widget: "string"}
      - {label: "tags", name: "tags", widget: "string"}
      - {label: "images", name: "images", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}

